# Generated by Django 3.2.9 on 2021-11-29 14:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('interview', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=100)),
            ],
        ),
        migrations.RenameField(
            model_name='city',
            old_name='distirct',
            new_name='district',
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=50)),
                ('mobile', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('address', models.TextField()),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='interview.city')),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='interview.district')),
                ('pincode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='interview.pincode')),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='interview.state')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post', models.CharField(max_length=100)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='interview.company')),
            ],
        ),
        migrations.CreateModel(
            name='PanelMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=50)),
                ('mobile', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('address', models.TextField()),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='interview.city')),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='interview.district')),
                ('pincode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='interview.pincode')),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='interview.state')),
            ],
        ),
        migrations.CreateModel(
            name='PanelAdmin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=50)),
                ('mobile', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('address', models.TextField()),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='interview.city')),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='interview.district')),
                ('pincode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='interview.pincode')),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='interview.state')),
            ],
        ),
        migrations.CreateModel(
            name='Interview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='interview.post')),
            ],
        ),
    ]
