# Generated by Django 3.2.9 on 2021-11-29 14:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('interview', '0002_auto_20211129_1408'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paneladmin',
            name='mobile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='interview.mobileverification'),
        ),
        migrations.AlterField(
            model_name='panelmember',
            name='mobile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='interview.mobileverification'),
        ),
        migrations.AlterField(
            model_name='user',
            name='mobile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='interview.mobileverification'),
        ),
    ]
